name: Windows RDP via NetBird (ON)

on:
  workflow_dispatch:
    inputs:
      rdp_user:
        description: "RDP Username"
        required: false
        default: "NbUser"
      rdp_pass:
        description: "RDP Password"
        required: false
        default: "NbPass@123"
      runtime_minutes:
        description: "RDP Alive Minutes (max 355)"
        required: false
        default: "355"

jobs:
  rdp:
    runs-on: windows-2022
    timeout-minutes: 370

    steps:
      - name: Install NetBird agent
        shell: pwsh
        run: |
          $url = "https://pkgs.netbird.io/windows/x64"
          $dst = "$env:TEMP\netbird-installer.exe"
          Invoke-WebRequest -Uri $url -OutFile $dst -UseBasicParsing
          Start-Process -FilePath $dst -ArgumentList "/S" -Wait

      - name: Connect runner to NetBird using setup key
        shell: pwsh
        run: |
          & "C:\Program Files\NetBird\netbird.exe" up --setup-key "${{ secrets.NETBIRD_SETUP_KEY }}"
          & "C:\Program Files\NetBird\netbird.exe" status

      - name: Create RDP User and Enable RDP
        shell: pwsh
        run: |
          $u = "${{ github.event.inputs.rdp_user }}"
          $p = "${{ github.event.inputs.rdp_pass }}"
          $sec = ConvertTo-SecureString $p -AsPlainText -Force
          if (-not (Get-LocalUser -Name $u -ErrorAction SilentlyContinue)) {
            New-LocalUser -Name $u -Password $sec -AccountNeverExpires
            Add-LocalGroupMember -Group Administrators -Member $u
            Add-LocalGroupMember -Group "Remote Desktop Users" -Member $u
          } else {
            Set-LocalUser -Name $u -Password $sec -AccountNeverExpires
            Enable-LocalUser -Name $u
          }
          Set-ItemProperty "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop" | Out-Null

      - name: Enable Windows Audio Service
        shell: pwsh
        run: |
          Set-Service -Name "Audiosrv" -StartupType Automatic
          Start-Service -Name "Audiosrv"

      - name: Downloading & Installing Essentials
        shell: cmd
        run: |
          curl -s -L -o C:\Users\Public\Desktop\Telegram.exe https://td.telegram.org/tx64/tsetup-x64.6.1.3.exe
          curl -s -L -o C:\Users\Public\Desktop\Winrar.exe https://www.rarlab.com/rar/winrar-x64-621.exe
          powershell -Command "Invoke-WebRequest 'https://github.com/chieunhatnang/VM-QuickConfig/releases/download/1.6.1/VMQuickConfig.exe' -OutFile 'C:\Users\Public\Desktop\VMQuickConfig.exe'"
          powershell -Command "Invoke-WebRequest 'https://install.speedtest.net/app/windows/latest/speedtestbyookla_x64.msi' -OutFile 'C:\Users\Public\Desktop\speedtestbyookla_x64.msi'"
          powershell -Command "Invoke-WebRequest 'https://mirror2.internetdownloadmanager.com/idman642build43.exe' -OutFile 'C:\Users\Public\Desktop\idman642build43.exe'"

          C:\Users\Public\Desktop\Telegram.exe /VERYSILENT /NORESTART
          msiexec.exe /i C:\Users\Public\Desktop\speedtestbyookla_x64.msi /quiet /norestart
          powershell -Command "Start-Process -FilePath 'C:\Users\Public\Desktop\idman642build43.exe' -ArgumentList '/S' -Wait"
          C:\Users\Public\Desktop\Winrar.exe /S

          del C:\Users\Public\Desktop\Winrar.exe
          del C:\Users\Public\Desktop\idman642build43.exe
          del C:\Users\Public\Desktop\speedtestbyookla_x64.msi

          del /f "C:\Users\Public\Desktop\Epic Games Launcher.lnk"
          del /f "C:\Users\Public\Desktop\Unity Hub.lnk"

      - name: Show NetBird IP
        shell: pwsh
        run: |
          & "C:\Program Files\NetBird\netbird.exe" status | Select-String "NetBird IP"

      - name: Keep RDP Session Alive
        shell: pwsh
        run: |
          $runtime = [int]"${{ github.event.inputs.runtime_minutes }}"
          if ($runtime -gt 355) { $runtime = 355 }
          $end = (Get-Date).AddMinutes($runtime)
          while ((Get-Date) -lt $end) {
            $left = [math]::Ceiling(($end - (Get-Date)).TotalMinutes)
            Write-Host "RDP alive... ($left min left)"
            Start-Sleep -Seconds 60
          }
          
