name: macOS Remote Access via NetBird

on:
  workflow_dispatch:
    inputs:
      rdpuser:
        description: 'Remote user name'
        required: false
        default: 'nbuser'
      rdppass:
        description: 'Remote user password'
        required: false
        default: 'NbPass123'
      runtimeminutes:
        description: 'Session alive time in minutes (max 355)'
        required: false
        default: 355

jobs:
  rdp:
    runs-on: macos-latest
    timeout-minutes: 370
    steps:
    - name: Install NetBird
      shell: bash
      run: |
        curl -fsSL https://pkgs.netbird.io/macos/amd64 -o netbird.pkg
        sudo installer -pkg netbird.pkg -target /
        rm netbird.pkg
        which netbird
        netbird version

    - name: Connect runner to NetBird using setup key (no service)
      shell: bash
      env:
        NETBIRDSETUPKEY: ${{ secrets.NETBIRDSETUPKEY }}
      run: |
        sudo netbird up --setup-key "$NETBIRDSETUPKEY"
        sleep 10
        sudo netbird status
        sudo netbird peers list

    - name: Create user and enable Screen Sharing
      shell: bash
      run: |
        username="${{ github.event.inputs.rdpuser }}"
        password="${{ github.event.inputs.rdppass }}"
        if ! dscl . -read /Users/"$username" > /dev/null 2>&1; then
          sudo dscl . -create /Users/"$username"
          sudo dscl . -create /Users/"$username" UserShell /bin/bash
          sudo dscl . -create /Users/"$username" RealName "$username"
          sudo dscl . -create /Users/"$username" UniqueID 1001
          sudo dscl . -create /Users/"$username" PrimaryGroupID 80
          sudo dscl . -create /Users/"$username" NFSHomeDirectory /Users/"$username"
          sudo dscl . -passwd /Users/"$username" "$password"
          sudo mkdir -p /Users/"$username"
          sudo chown "$username":staff /Users/"$username"
          sudo dscl . -append /Groups/admin GroupMembership "$username"
        else
          sudo dscl . -passwd /Users/"$username" "$password"
        fi

    - name: Enable Screen Sharing and Remote Management
      shell: bash
      run: |
        username="${{ github.event.inputs.rdpuser }}"
        sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
          -activate -configure -access -on \
          -users "$username" -privs -all \
          -restart -agent -menu
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
          -configure -allowAccessFor -specifiedUsers

    - name: Display connection information
      shell: bash
      run: |
        echo "=== NetBird Status ==="
        sudo netbird status || true
        echo "=== NetBird Peers ==="
        sudo netbird peers list || true
        echo "=== Network Interfaces ==="
        ifconfig | grep -A 1 "netbird\|utun"
        echo "=== Screen Sharing Status ==="
        sudo launchctl print system/com.apple.screensharing
        echo "Username: ${{ github.event.inputs.rdpuser }}"
        echo "Password: ${{ github.event.inputs.rdppass }}"
        echo "Use VNC client to connect to the NetBird IP shown above"

    - name: Keep session alive for specified runtime
      shell: bash
      run: |
        runtime_minutes=${{ github.event.inputs.runtimeminutes }}
        if [ "$runtime_minutes" -gt 355 ]; then
          runtime_minutes=355
        fi
        end_time=$((SECONDS + runtime_minutes * 60))
        while [ $SECONDS -lt $end_time ]; do
          remaining_minutes=$(( (end_time - SECONDS) / 60 ))
          echo "Remote session alive... $remaining_minutes minutes left"
          if [ $((remaining_minutes % 5)) -eq 0 ]; then
            echo "=== NetBird Status Update ==="
            sudo netbird status || true
          fi
          sleep 60
        done
        echo "Session timeout reached. Cleaning up..."
        sudo netbird down || true
        
